apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        #securityContext:
        #  privileged: true
        #command: ["/bin/bash", "-c", "--"]
        #args:
        #- mkdir -p /var/www/html/repos/{base,centosplus,extras,updates};
        #  mount -t overlay repo /var/www/html/repos;
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log
        - mountPath: /var/www/html/repos
          name: repo
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf # place configMap nginx-conf in /etc/nginx
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: virtualhost.conf
            path: virtualhost/virtualhost.conf 
      - name: log
        emptyDir: {} 
      - name: repo
        hostPath: 
          path: /var/www/html/repos
