apiVersion: v1
kind: Service
metadata:
  name: ngnix-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  externalIPs: 
  - 172.16.21.19
  selector:
    app: nginx
